apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop
  labels:
    role: api
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
        - name: api
          image: 440744253012.dkr.ecr.eu-north-1.amazonaws.com/lms-backend:${GITHUB_SHA}
          imagePullPolicy: Always
          env:
            - name: MONGO_CONN_STR
              value: mongodb://mongodb-svc:27017/LMS?directConnection=true
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: password
          #envFrom:
          #  - secretRef:
          #    name: app-secrets 
          ports:
            - containerPort: 5001
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1

